input {
  file {
    path => "/home/anirudh/ELK-Observability-Assignment/Part5/Q4/sample-app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => [
        "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:log_level} %{WORD:service_name} %{HOSTNAME:host_name} %{GREEDYDATA:message_text}",
        "\[%{TIMESTAMP_ISO8601:timestamp}\] %{LOGLEVEL:log_level} %{WORD:service_name} %{HOSTNAME:host_name} %{GREEDYDATA:message_text} response_code=%{NUMBER:response_code} response_time_ms=%{NUMBER:response_time_ms}",
        "%{TIMESTAMP_ISO8601:timestamp} \| %{LOGLEVEL:log_level} \| %{WORD:service_name} \| %{HOSTNAME:host_name} \| %{DATA:message_text} \| %{NUMBER:response_code} \| %{NUMBER:response_time_ms}"
      ]
    }
  }

  date {
    match => [ "timestamp", "ISO8601", "yyyy-MM-dd HH:mm:ss" ]
    target => "@timestamp"
  }

  if [response_code] {
    mutate {
      convert => { "response_code" => "integer" }
    }
  }

  if [response_time_ms] {
    mutate {
      convert => { "response_time_ms" => "integer" }
    }
  }

  if "_grokparsefailure" in [tags] {
    mutate {
      add_tag => [ "unparsed_log" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://172.20.0.2:9200"]
    index => "sample-app-logs"
  }

  stdout {
    codec => rubydebug
  }
}
